import * as types from './types';

export const languages = [
  { code: 'en', name: 'English' },
  { code: 'ar', name: 'العربية' },
  { code: 'fr', name: 'Français' },
  { code: 'es', name: 'Español' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ur', name: 'اردو' },
  { code: 'ru', name: 'Русский' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
  { code: 'pt', name: 'Português' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'fa', name: 'فارسی' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'it', name: 'Italiano' },
  { code: 'ko', name: '한국어' },
  { code: 'sv', name: 'Svenska' },
  { code: 'pl', name: 'Polski' },
];

export const currencies = [
  { code: 'USD', name: 'United States Dollar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'AED', name: 'UAE Dirham' },
  { code: 'QAR', name: 'Qatari Riyal' },
  { code: 'KWD', name: 'Kuwaiti Dinar' },
  { code: 'BHD', name: 'Bahraini Dinar' },
  { code: 'OMR', name: 'Omani Rial' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'RUB', name: 'Russian Ruble' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'SGD', name: 'Singapore Dollar' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'ZAR', name: 'South African Rand' },
];

export const countries = [
    { code: "AF", name: "Afghanistan", key: "country_af" },
    { code: "AL", name: "Albania", key: "country_al" },
    { code: "DZ", name: "Algeria", key: "country_dz" },
    { code: "AD", name: "Andorra", key: "country_ad" },
    { code: "AO", name: "Angola", key: "country_ao" },
    { code: "AR", name: "Argentina", key: "country_ar" },
    { code: "AM", name: "Armenia", key: "country_am" },
    { code: "AU", name: "Australia", key: "country_au" },
    { code: "AT", name: "Austria", key: "country_at" },
    { code: "AZ", name: "Azerbaijan", key: "country_az" },
    { code: "BS", name: "Bahamas", key: "country_bs" },
    { code: "BH", name: "Bahrain", key: "country_bh" },
    { code: "BD", name: "Bangladesh", key: "country_bd" },
    { code: "BY", name: "Belarus", key: "country_by" },
    { code: "BE", name: "Belgium", key: "country_be" },
    { code: "BT", name: "Bhutan", key: "country_bt" },
    { code: "BO", name: "Bolivia", key: "country_bo" },
    { code: "BA", name: "Bosnia and Herzegovina", key: "country_ba" },
    { code: "BR", name: "Brazil", key: "country_br" },
    { code: "BG", name: "Bulgaria", key: "country_bg" },
    { code: "KH", name: "Cambodia", key: "country_kh" },
    { code: "CM", name: "Cameroon", key: "country_cm" },
    { code: "CA", name: "Canada", key: "country_ca" },
    { code: "CF", name: "Central African Republic", key: "country_cf" },
    { code: "CL", name: "Chile", key: "country_cl" },
    { code: "CN", name: "China", key: "country_cn" },
    { code: "CO", name: "Colombia", key: "country_co" },
    { code: "CR", name: "Costa Rica", key: "country_cr" },
    { code: "HR", name: "Croatia", key: "country_hr" },
    { code: "CU", name: "Cuba", key: "country_cu" },
    { code: "CY", name: "Cyprus", key: "country_cy" },
    { code: "CZ", name: "Czech Republic", key: "country_cz" },
    { code: "DK", name: "Denmark", key: "country_dk" },
    { code: "DO", name: "Dominican Republic", key: "country_do" },
    { code: "EC", name: "Ecuador", key: "country_ec" },
    { code: "EG", name: "Egypt", key: "country_eg" },
    { code: "SV", name: "El Salvador", key: "country_sv" },
    { code: "EE", name: "Estonia", key: "country_ee" },
    { code: "ET", name: "Ethiopia", key: "country_et" },
    { code: "FI", name: "Finland", key: "country_fi" },
    { code: "FR", name: "France", key: "country_fr" },
    { code: "GE", name: "Georgia", key: "country_ge" },
    { code: "DE", name: "Germany", key: "country_de" },
    { code: "GH", name: "Ghana", key: "country_gh" },
    { code: "GR", name: "Greece", key: "country_gr" },
    { code: "GT", name: "Guatemala", key: "country_gt" },
    { code: "HN", name: "Honduras", key: "country_hn" },
    { code: "HU", name: "Hungary", key: "country_hu" },
    { code: "IS", name: "Iceland", key: "country_is" },
    { code: "IN", name: "India", key: "country_in" },
    { code: "ID", name: "Indonesia", key: "country_id" },
    { code: "IR", name: "Iran", key: "country_ir" },
    { code: "IQ", name: "Iraq", key: "country_iq" },
    { code: "IE", name: "Ireland", key: "country_ie" },
    { code: "IL", name: "Israel", key: "country_il" },
    { code: "IT", name: "Italy", key: "country_it" },
    { code: "JP", name: "Japan", key: "country_jp" },
    { code: "JO", name: "Jordan", key: "country_jo" },
    { code: "KZ", name: "Kazakhstan", key: "country_kz" },
    { code: "KE", name: "Kenya", key: "country_ke" },
    { code: "KW", name: "Kuwait", key: "country_kw" },
    { code: "LV", name: "Latvia", key: "country_lv" },
    { code: "LB", name: "Lebanon", key: "country_lb" },
    { code: "LY", name: "Libya", key: "country_ly" },
    { code: "LT", name: "Lithuania", key: "country_lt" },
    { code: "LU", name: "Luxembourg", key: "country_lu" },
    { code: "MY", name: "Malaysia", key: "country_my" },
    { code: "MX", name: "Mexico", key: "country_mx" },
    { code: "MN", name: "Mongolia", key: "country_mn" },
    { code: "ME", name: "Montenegro", key: "country_me" },
    { code: "MA", name: "Morocco", key: "country_ma" },
    { code: "MM", name: "Myanmar", key: "country_mm" },
    { code: "NP", name: "Nepal", key: "country_np" },
    { code: "NL", name: "Netherlands", key: "country_nl" },
    { code: "NZ", name: "New Zealand", key: "country_nz" },
    { code: "NG", name: "Nigeria", key: "country_ng" },
    { code: "NO", name: "Norway", key: "country_no" },
    { code: "OM", name: "Oman", key: "country_om" },
    { code: "PK", name: "Pakistan", key: "country_pk" },
    { code: "PA", name: "Panama", key: "country_pa" },
    { code: "PY", name: "Paraguay", key: "country_py" },
    { code: "PE", name: "Peru", key: "country_pe" },
    { code: "PH", name: "Philippines", key: "country_ph" },
    { code: "PL", name: "Poland", key: "country_pl" },
    { code: "PT", name: "Portugal", key: "country_pt" },
    { code: "QA", name: "Qatar", key: "country_qa" },
    { code: "RO", name: "Romania", key: "country_ro" },
    { code: "RU", name: "Russia", key: "country_ru" },
    { code: "SA", name: "Saudi Arabia", key: "country_sa" },
    { code: "SN", name: "Senegal", key: "country_sn" },
    { code: "RS", name: "Serbia", key: "country_rs" },
    { code: "SG", name: "Singapore", key: "country_sg" },
    { code: "SK", name: "Slovakia", key: "country_sk" },
    { code: "SI", name: "Slovenia", key: "country_si" },
    { code: "ZA", name: "South Africa", key: "country_za" },
    { code: "KR", name: "South Korea", key: "country_kr" },
    { code: "ES", name: "Spain", key: "country_es" },
    { code: "LK", name: "Sri Lanka", key: "country_lk" },
    { code: "SD", name: "Sudan", key: "country_sd" },
    { code: "SE", name: "Sweden", key: "country_se" },
    { code: "CH", name: "Switzerland", key: "country_ch" },
    { code: "SY", name: "Syria", key: "country_sy" },
    { code: "TW", name: "Taiwan", key: "country_tw" },
    { code: "TH", name: "Thailand", key: "country_th" },
    { code: "TR", name: "Turkey", key: "country_tr" },
    { code: "UA", name: "Ukraine", key: "country_ua" },
    { code: "AE", name: "United Arab Emirates", key: "country_ae" },
    { code: "GB", name: "United Kingdom", key: "country_gb" },
    { code: "US", name: "United States", key: "country_us" },
    { code: "UY", name: "Uruguay", key: "country_uy" },
    { code: "UZ", name: "Uzbekistan", key: "country_uz" },
    { code: "VE", name: "Venezuela", key: "country_ve" },
    { code: "VN", name: "Vietnam", key: "country_vn" },
    { code: "YE", name: "Yemen", key: "country_ye" },
];

export const religionOptions = Object.values(types.Religion).map(value => ({ value, key: `religion_${value.toLowerCase()}` }));
export const genderSelectOptions = Object.values(types.Gender).map(value => ({ value, key: `gender_${value.toLowerCase()}` }));
export const maritalStatusOptions = Object.values(types.MaritalStatus).map(value => ({ value, key: `marital_status_${value.toLowerCase().replace(/\s/g, '_')}` }));
export const beneficiaryRelationOptions = Object.values(types.BeneficiaryRelation).map(value => ({ value, key: `relation_${value.toLowerCase()}` }));
export const assetTypeOptions = Object.values(types.AssetType).map(value => ({ value, key: `asset_type_${value.toLowerCase().replace(/[\s/]/g, '_')}` }));
export const reminderOptions = ['none', '3-months', '6-months', '1-year', '3-years', '5-years'].map(value => ({ value, key: `reminder_${value.replace(/-/g, '_')}` }));


export const willFormSteps = [
    { id: 1, titleKey: 'personal_details' },
    { id: 2, titleKey: 'beneficiaries' },
    { id: 3, titleKey: 'debts' },
    { id: 4, titleKey: 'assets' },
    { id: 5, titleKey: 'will_content' },
    { id: 6, titleKey: 'media_messages' },
    { id: 7, titleKey: 'legal_and_witnesses' },
    { id: 8, titleKey: 'final_instructions' },
];